{% set python_min = "3.11" %}
{% set name = "hydromt_wflow" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hydromt_wflow-{{ version }}.tar.gz
  sha256: 4b20612c5b12ac27109fb63865d4fbffc77a11a72c63ad410b4e2b2bc7bc920f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools >=61
    - wheel
    - python {{ python_min }}
  run:
    - dask
    - geopandas >=0.10
    - hydromt >=1.3.0
    - numpy
    - pandas
    - pyflwdir >=0.5.7
    - pyproj
    - python >={{ python_min }}
    - pooch
    - scipy
    - shapely
    - xarray

test:
  imports:
    - hydromt_wflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/hydromt_wflow/
  summary: HydroMT plugin for wflow models.
  dev_url: https://github.com/Deltares/hydromt_wflow
  doc_url: https://deltares.github.io/hydromt_wflow/stable/
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tjalling-dejong
    - deltares-service-account
    - dalmijn
    - JoostBuitink
    - DirkEilander
    - hboisgon
    - LuukBlom
