{% set python_min = "3.10" %}
{% set name = "hydromt_wflow" %}
{% set version = "1.0.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hydromt_wflow-{{ version }}.tar.gz
  sha256: b238803069031dcf556e7a068d286078b02c7c2ff6232fecffe386d7f012c612

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit >=3.4.0,<4
    - python {{ python_min }}
  run:
    - dask
    - geopandas >=0.10
    - hydromt >=0.10.1,<0.11
    - numpy
    - pandas
    - pyflwdir >=0.5.7
    - pyproj
    - python >={{ python_min }},<3.12
    - scipy
    - shapely
    - tomlkit >=0.13.3
    - xarray

test:
  imports:
    - hydromt_wflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/hydromt_wflow/
  summary: HydroMT plugin for wflow models.
  dev_url: https://github.com/Deltares/hydromt_wflow
  doc_url: https://deltares.github.io/hydromt_wflow/stable/
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tjalling-dejong
    - deltares-service-account
    - dalmijn
    - JoostBuitink
    - DirkEilander
    - hboisgon
