{% set python_min = "3.11" %}
{% set name = "hydromt_wflow" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hydromt_wflow-{{ version }}.tar.gz
  sha256: d187f7317de952ba07ae36b484b900f88b1e0f4f5de5f1a368bedc88db9c23f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit >=3.4.0,<4
    - python {{ python_min }}
  run:
    - dask
    - geopandas >=0.10
    - hydromt >=1.3.0
    - numpy
    - pandas
    - pyflwdir >=0.5.7
    - pyproj
    - python >={{ python_min }}
    - pooch
    - scipy
    - shapely
    - xarray

test:
  imports:
    - hydromt_wflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/hydromt_wflow/
  summary: HydroMT plugin for wflow models.
  dev_url: https://github.com/Deltares/hydromt_wflow
  doc_url: https://deltares.github.io/hydromt_wflow/stable/
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tjalling-dejong
    - deltares-service-account
    - dalmijn
    - JoostBuitink
    - DirkEilander
    - hboisgon
    - LuukBlom
    
