{% set name = "hydromt_wflow" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hydromt_wflow-{{ version }}.tar.gz
  sha256: 6b76bd7bb0d3637a657cba3d5f9d4832c5e6d7b2f861dc9dd680ac12fb25bce1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.9
  run:
    - dask
    - geopandas >=0.10
    - hydromt >=0.9.4,<0.11
    - netcdf4
    - numpy >=1.23,<2
    - pandas
    - pyflwdir >=0.5.7
    - pyproj
    - python >=3.9,<3.12
    - rioxarray
    - scipy
    - shapely
    - toml
    - xarray <=2024.3.0

test:
  imports:
    - hydromt_wflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/hydromt_wflow/
  summary: hydroMT plugin for wflow models.
  dev_url: https://github.com/Deltares/hydromt_wflow
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deltares-service-account
    - dalmijn
    - JoostBuitink
    - DirkEilander
    - hboisgon
