{% set python_min = "3.10" %}
{% set name = "hydromt_wflow" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hydromt_wflow-{{ version }}.tar.gz
  sha256: 6613c35c1f54b29266d249b92be7e8d10d6f6ca8779875899627976747e0f24d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python {{ python_min }}
  run:
    - dask
    - geopandas >=0.10
    - hydromt >=0.9.4,<0.11
    - netcdf4
    - numpy >=1.23,<2
    - pandas
    - pyflwdir >=0.5.7
    - pyproj
    - python >={{ python_min }},<3.12
    - rioxarray <=0.17.0
    - scipy
    - shapely
    - toml
    - xarray <=2024.3.0

test:
  imports:
    - hydromt_wflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/hydromt_wflow/
  summary: hydroMT plugin for wflow models.
  dev_url: https://github.com/Deltares/hydromt_wflow
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deltares-service-account
    - dalmijn
    - JoostBuitink
    - DirkEilander
    - hboisgon
