{% set name = "hydromt_wflow" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydromt_wflow-{{ version }}.tar.gz
  sha256: 35c8634826444df3a3217542d3aaa384f9420f2217c2830f7ea7c3d7eed9988e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.9
  run:
    - dask
    - geopandas >=0.10
    - hydromt >=0.9.1,<0.10
    - netcdf4
    - numpy
    - pandas
    - pyflwdir >=0.5.7
    - pyproj
    - python >=3.8
    - rioxarray
    - scipy
    - shapely
    - toml
    - xarray
    - pip:
      - hydroengine

test:
  imports:
    - hydromt_wflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/hydromt_wflow/
  summary: hydroMT plugin for wflow models.
  dev_url: https://github.com/Deltares/hydromt_wflow
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalmijn
    - JoostBuitink
    - DirkEilander
    - hboisgon
